create table if not exists registrations (
  id bigint generated by default as identity primary key,
  code text unique not null,
  amount bigint not null check (amount = 10000000),
  status text not null default 'pending' check (status in ('pending','paid','expired','cancelled')),
  name text not null, school text not null, role text not null, email text not null, phone text not null,
  details text, sepay_transaction_id bigint unique, created_at timestamptz not null default now(), paid_at timestamptz
);
